// Generated by CoffeeScript 2.7.0
  // spaced-rep.coffee
import {
  undef
} from '@jdeighan/base-utils';

import {
  hZhWords
} from '@jdeighan/spaced-rep/words';

// ---------------------------------------------------------------------------
export var getNextWord = (hState = {}) => {
  return hZhWords.一;
};
